[build]
  command = "npm run build"
  publish = "dist"

# (se for usar proxy para sua API, coloque aqui ANTES do fallback)
# [[redirects]]
#   from = "/api/*"
#   to = "https://SEU-SUBDOMINIO.up.railway.app/:splat"
#   status = 200
#   force = true

# Fallback de SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
